# Site settings
title: SiteWorks Contracting
email: info@siteworks.com
description: "SiteWorks - contracting in the greater Westchester area. Call us for all of your site work needs."
baseurl: "/Siteworks"
url: "http://siteworks.com"
twitter_username: siteworks
facebook_username:  siteworks
instagram_username: siteworks

phone: 9149438239
fax: 9149438239


# Build settings
markdown: kramdown
permalink: pretty

# Sass
sass:
    style: compressed
